name: bitrisesample
description: "A new Flutter project for iOS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # ปรับรองรับ Dart 3 & Flutter ยุคปัจจุบัน

dependencies:
  flutter:
    sdk: flutter

  # ไอคอนสไตล์ iOS สำหรับใช้ร่วมกับ Cupertino Widget
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # หากในอนาคตต้องการเพิ่มรูปภาพ ให้ปลดเครื่องหมาย # สองบรรทัดล่างนี้ออกครับ
  # assets:
  #   - assets/images/
