name: Build and Deploy PHP

on:
  workflow_dispatch:
    inputs:
      ftp_server:
        description: 'FTP Host/Server'
        required: true
        default: 'ftp.f1x3r.org'
      ftp_username:
        description: 'FTP Username'
        required: true
      ftp_password:
        description: 'FTP Password'
        required: true
        # 🟢 ลบ type: boolean ออก เพื่อให้เปลี่ยนจากสวิตช์เป็นช่องพิมพ์ข้อความปกติ
        type: string 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. ดึงโค้ดจาก Repo เข้ามา
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. ตั้งค่า PHP และ Composer
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.33'

    # 3. ติดตั้ง Library ด้วย Composer (สร้างโฟลเดอร์ vendor)
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

    # 4. ส่งไฟล์ทั้งหมดขึ้น Server ผ่าน FTP
    - name: Sync files to Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ inputs.ftp_server }}
        username: ${{ inputs.ftp_username }}
        password: ${{ inputs.ftp_password }}
        server-dir: /public_html/patches/
